FROM stackbrew/ubuntu:14.04

ENV DEBIAN_FRONTEND noninteractive
ENV HOME /root
ENV PATH /usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin

RUN apt-get update -y && apt-get install -y python python-netifaces

ADD bin/tory-register /usr/local/bin/tory-register

WORKDIR /root
CMD ["tory-register"]
