#!/usr/bin/env python
from __future__ import print_function

import argparse
import os
import sys

try:
    from urllib.request import urlopen
    import urllib.parse as urlparse
except ImportError:
    from urllib import urlopen
    import urlparse


def main(sysargs=sys.argv[:]):
    parser = argparse.ArgumentParser()
    parser.add_argument('--host', dest='hostname')
    parser.add_argument('--list', dest='list_only', action='store_true')
    parser.add_argument(
        '-s',
        '--tory-server',
        metavar='TORY_SERVER',
        default=os.environ.get(
            'TORY_SERVER', 'http://localhost:9462/ansible/hosts'
        )
    )

    args = parser.parse_args(sysargs[1:])
    scheme, netloc, path, params, query, fragment = \
        urlparse.urlparse(args.tory_server)

    if args.hostname:
        path += ('/' + args.hostname)
        if query:
            query += '&vars-only=1'
        else:
            query = 'vars-only=1'

    elif not args.list_only:
        if query:
            query += '&exclude-vars=1'
        else:
            query = 'exclude-vars=1'

    url = urlparse.urlunparse(
        urlparse.ParseResult(scheme, netloc, path, params, query, fragment)
    )

    print(urlopen(url).read())
    return 0


if __name__ == '__main__':
    sys.exit(main())
