#!/usr/bin/env ruby

require 'json'
require 'net/http'
require 'uri'

def main
  uri = URI(ARGV.first)

  parsed = JSON.parse($stdin.read)
  $stderr.puts("Parsed input length: #{parsed.length}")

  parsed.each do |host|
    conn = Net::HTTP.new(uri.host, uri.port)
    req = Net::HTTP::Post.new(uri.request_uri)
    req.body = {
      'host' => {
        'name' => host['name'],
        'package' => host['package'],
        'image' => host['image'],
        'type' => host['type'],
        'ip' => host['primaryIp'],
        'tags' => Hash[host['tags'].map { |k,v| ["#{k}", "#{v}"] }],
        'attrs' => {
          'disk' => "#{host['disk']}",
          'memory' => "#{host['memory']}"
        }
      }
    }.to_json
    req['Content-Type'] = 'application/json'
    resp = conn.request(req)
    if resp.code != '201'
      $stderr.puts("Failed to create host #{host['name']}: #{resp.inspect}")
    else
      $stderr.puts("Added host #{host['name']}")
    end
  end
end

main if __FILE__ == $0
